Implemented feature/get_feed_updates(), which will return a list of d…
tomquirk/linkedin-api pull request #115
Opened 2020-08-31 10:50 UTC by keducoop

Hi there.

First of all many thanks for your time, I really appreciate it.

Second kindly remove pull request #114, since this pull request enhances that one.

This feature implements a function which returns a list of dictionaries, each one of them corresponding to a post present in the feed, sorted by 'Recent'.

2020-09-08 13:32 UTC, tomquirk commented
This is awesome @keducoop  thank you! I will get to reviewing this shortly

2020-09-09 22:48 UTC, tomquirk requested changes
Hi @keducoop, AWESOME work on this, I can't wait to have this feature!

I left a few comments for your consideration. Could you please add a test or 2 for this as well? Thanks.

Also, please consider joining our Slack community 👉https://join.slack.com/t/linkedinapi/shared_invite/zt-h7tny6r6-kQILMuCX3Zwjecnz0IbYCQ

2020-09-09 22:48 UTC, tomquirk commented on linkedin_api/linkedin.py
> +    def get_feed_updates(self, limit = -1, offset = 0, is_skip_promoted = True):
**nitpick**: can we please change the `is_skip_promoted` variable to `exclude_promoted_posts` or similar? I'd like this to be a bit more descriptive 😄

2020-09-09 22:48 UTC, tomquirk commented on linkedin_api/utils/helpers.py
> +def get_update_author_name(d_included):
**Praise**: I _really_ like this utility-driven approach to parsing the data!

2020-09-10 16:11 UTC, keducoop commented on linkedin_api/utils/helpers.py
> +def get_update_old(d_included):
The `old` is the field that is being returned by the API as string and express the amount of time in human readable words that passed since the post was initially published.

Some examples:

* "11m"
* "Promoted" (special case, a promotion)
* "18m . edited"
* "21h"
* "1d"

2020-09-10 16:13 UTC, keducoop commented on linkedin_api/linkedin.py
> +    def get_feed_updates(self, limit = -1, offset = 0, is_skip_promoted = True):
Sure, I used to use the "is_" to name a parameter which accepts boolean values.

2020-09-10 16:17 UTC, keducoop commented
@tomquirk sorry for bother you again, but I have an improved version.

If you don't mind kindly close this pull request, and I will submit a new one which will incorporate your [comment](https://github.com/tomquirk/linkedin-api/pull/115#discussion_r485962201).

Also I will really appreciate if you provide me some examples about tests to also incorporate them in the new pull request.

Many thanks.

2020-09-12 07:21 UTC, closed without merging