fetch all posts made by an account
tomquirk/linkedin-api pull request #181
Opened 2021-09-16 19:07 UTC by alvaroserrrano

2021-09-17 05:58 UTC, abinpaul1 requested changes

2021-09-17 05:58 UTC, abinpaul1 commented on linkedin_api/linkedin.py
> +    def get_profile_posts(self, public_id=None, urn_id=None):
Great. This looks good for a start. 
I see you use the `paginationToken` from the first request to get the next 10. So the user gets a total of only 20 recent posts. 
We could provide an option to let the user decide how many posts he wants (by having a count parameter for the function) . We could keep doing the request till we run out of posts or the user supplied count is over. What do you think?

2021-09-17 05:58 UTC, abinpaul1 commented on linkedin_api/linkedin.py
> +            "count": 10,
Whats your opinion on having a constant like ` _MAX_POST_COUNT` to decide the number of posts we can fetch in a single request. I think the maximum would be around 100 or 50. We would have to verify that by trial.
This way we could fetch the required number of posts in fewer number of requests,

2021-09-17 05:58 UTC, abinpaul1 commented on linkedin_api/linkedin.py
> -    sleep(random.randint(2, 5))  # sleep a random duration to try and evade suspention
Please keep this lines the same

2021-09-17 05:58 UTC, abinpaul1 commented on linkedin_api/linkedin.py
> +                profile["displayPictureUrl"] = profile["miniProfile"][
Please keep these lines the same as well.

2021-09-17 05:58 UTC, abinpaul1 commented on linkedin_api/linkedin.py
> -            public_id=public_id, urn_id=urn_id, results=results, max_results=max_results
Similar issue here. Please try to keep lines you are not changing in the same format as before. It really helps later on in case of maintenance later on.

2021-09-17 18:38 UTC, alvaroserrrano commented on linkedin_api/linkedin.py
> +            "count": 10,
Awesome! Will try to implement it.
 I believe my last commit should fix that, but for some reason I am getting 106 instead of the hardcoded max of 100

2021-09-17 18:39 UTC, alvaroserrrano commented on linkedin_api/linkedin.py
> -            public_id=public_id, urn_id=urn_id, results=results, max_results=max_results
Sorry. I apologize for that. The editor formatted on save because I forgot to disable the workspace settings.

2021-09-18 16:01 UTC, abinpaul1 commented on linkedin_api/linkedin.py
> -    sleep(random.randint(2, 5))  # sleep a random duration to try and evade suspention
This lines still seems changed.

2021-09-18 17:00 UTC, abinpaul1 commented
There seems to be a confusion. The `_MAX_POST_COUNT` variable was meant to indicate the maximum number of posts we could fetch in a SINGLE request (This is a limit set by Linkedin). So in the `url_params` we could have count upto a maximum of `_MAX_POST_COUNT`. Also if the user supplied value is less we should only fetch that many. So the `url_params` initially could have maybe min(_MAX_POST_COUNT, post_count). What do you think?

Since the post_count parameter taken as argument is for the user to specify how many posts he wants to be fetched. I think a deafult value of 10 or 15 would be enough.

We would exit the while loop when we have enough posts as mentioned by the user. (I dont think the second condition you have mentioned is needed)

A few more minor updates as well :
- Update the doc string to mention the count parameter
- Consider moving the constant `_MAX_POST_COUNT` to the top where all other constants `_MAX...` are declared
- The extra changes on some other lines are still there. Please fix that. You could try doing a `git diff master` to quickly look and ensure if only the required lines have been added and other lines have not changed.

Have a look at why the build failed. I believe you have access. This is the [link](https://app.travis-ci.com/github/tomquirk/linkedin-api/builds/237938263). Its basically a formatting check using `black`. Try running it locally before commiting to ensure all checks pass as well.

2021-09-19 03:38 UTC, abinpaul1 commented on linkedin_api/linkedin.py
> +            "count": min(10, self._MAX_POST_COUNT),
Shouldn't this be `min(post_count, self._MAX_POST_COUNT)`?

2021-09-19 03:40 UTC, abinpaul1 commented
Good work. Thanks a lot for taking the time to make the changes.
Just a couple more things that we might need to look at.
- Currently we return back the entire result including the `metadata` and `paging` as a dictionary. Should we do that or maybe return only the list of posts, ie, `return data['elements']`?

2021-09-19 03:49 UTC, abinpaul1 commented on linkedin_api/linkedin.py
> +            url_params["start"] = url_params["start"] + 10
Lets take a scenario here.
Suppose the user wants to fetch 230 posts.  
- Currenly in the first request he would get `min(230, 100)` ie, 100 posts. 
- In the next request his `start` parameter would be 100 `count` could be 100. This would get him another 100 posts for a total of 200 posts. 
- The third request his `start` would be 200 and `count` preferrably 30 (we could also keep this same as 100 to reduce the logic required and return back a total of 300 posts as well. This would also be fine. We could just maybe mention it in the documentation about it afterwards) to get a total of 230 posts to return to the user.
Let me know if this makes sense or if you have any other suggestions for a better flow/

2021-09-19 12:08 UTC, alvaroserrrano commented on linkedin_api/linkedin.py
> +            "count": min(10, self._MAX_POST_COUNT),
You are right, I'll change that

2021-09-19 12:12 UTC, alvaroserrrano commented
> Good work. Thanks a lot for taking the time to make the changes.
> Just a couple more things that we might need to look at.
> 
> * Currently we return back the entire result including the `metadata` and `paging` as a dictionary. Should we do that or maybe return only the list of posts, ie, `return data['elements']`?

I would return only the list of posts inside `data["elements"]`. If I were to use this API from an external application I would not care much about the `metadata` and `paging` since this API has already handled all that kind of stuff to fetch all the posts and it might be confusing for some users of the API that might see those fields and not know what they are about.

I changed the code to return only the list of posts at `data["elements"]`. Let me know what you think and we can return also `metadata` and `paging` if you consider so.

2021-09-19 12:20 UTC, alvaroserrrano commented on linkedin_api/linkedin.py
> +            url_params["start"] = url_params["start"] + 10
From what I understand, you mention the increment of 10 because of the bug that you mentioned above where I was doing `min(10, self._MAX_POST_COUNT)` instead of `min(post_count, self._MAX_POST_COUNT)`. Is that correct?

2021-09-19 15:05 UTC, abinpaul1 commented on linkedin_api/linkedin.py
> +            url_params["start"] = url_params["start"] + 10
I mentioned 10 because of this line `url_params["start"] = url_params["start"] + 10`.
Correct me if I am wrong. As it stands now, we fetch the first `_MAX_POST_COUNT = 100` posts and then change `start` to  `start + 10` in the next request, this will again fetch 100 posts starting from the 10th post. We end up getting (10th post to 110th post) when we actually need (100th post to 200th post).

2021-09-19 15:07 UTC, abinpaul1 commented on linkedin_api/linkedin.py
> +        :return: data in json format
We are now returning a list of posts right?

2021-09-19 15:08 UTC, abinpaul1 commented
> > Good work. Thanks a lot for taking the time to make the changes.
> > Just a couple more things that we might need to look at.
> > 
> > * Currently we return back the entire result including the `metadata` and `paging` as a dictionary. Should we do that or maybe return only the list of posts, ie, `return data['elements']`?
> 
> I would return only the list of posts inside `data["elements"]`. If I were to use this API from an external application I would not care much about the `metadata` and `paging` since this API has already handled all that kind of stuff to fetch all the posts and it might be confusing for some users of the API that might see those fields and not know what they are about.
> 
> I changed the code to return only the list of posts at `data["elements"]`. Let me know what you think and we can return also `metadata` and `paging` if you consider so.

Cool! We'll keep it like this.

2021-09-19 17:01 UTC, alvaroserrrano commented on linkedin_api/linkedin.py
> +            url_params["start"] = url_params["start"] + 10
I see. We should use _MAX_POST_COUNT there, right?

2021-09-19 17:11 UTC, abinpaul1 commented
This looks good.
Default post_count could be a lesser value, preferably 10 or 15.
Otherwise it looks good to merge. Good job 👍 and thanks for this.

2021-09-19 18:44 UTC, abinpaul1 commented
I tested this out locally and there seems to be a few minor issues.
- When I keep count as say 10, i get 20 posts. I believe this could be fixed if you brought the break condition to the beggining of the while loop
```python
while data and data["metadata"]["paginationToken"] != "":
    if len(data["elements"]) >= post_count:
        break
    ..
```
- One other thing we could do is to use the urn_id directly if the user provides it.
```python
if urn_id:
    profile_urn = "urn:li:fsd_profile:{}".format(urn_id)
else:
    profile = self.get_profile(public_id=public_id)
    profile_urn = profile["profile_urn"].replace(
        "fs_miniProfile", "fsd_profile"
    )
```

2021-09-19 18:58 UTC, abinpaul1 commented on linkedin_api/linkedin.py
> +            if len(data["elements"]) > post_count:
>= post_count

2021-09-19 22:47 UTC, alvaroserrrano commented on linkedin_api/linkedin.py
> +            if len(data["elements"]) > post_count:
Thanks! This PR is 90% yours. Thanks a lot for helping me get on board. I believe this is a good project that should gain more attention. Do not hesitate to let me know about any other feature, bug, or anything that I might contribute to.

2021-09-20 08:56 UTC, abinpaul1 commented on linkedin_api/linkedin.py
> +            if len(data["elements"]) > post_count:
Cool. Feel free to take up any issue or feature you think looks interesting. I currently don't have anything in particular to point you towards.

2021-09-20 08:57 UTC, merged

2021-10-04 12:29 UTC, alvaroserrrano commented
Since the PR was merged, do you know if I could access it by updating the library from pypy or using poetry? Or should I use the git source directly?

2021-10-04 13:40 UTC, alvaroserrrano commented
I am noticing that all the comments arrays are empty despite numCount being greater than 0. Do you know any reason why it might happen?

2021-10-04 15:07 UTC, abinpaul1 commented
I think it's because we are fetching the feed here. In the feed LinkedIn just displays the number of likes and comments and sometimes maybe a couple of comments. That must be the count you see in the returned result. 
You get back the URN of the post, I think you can use that to get full details of the post. I dont think that endpoint is implemented yet in linkedin-api.

2021-10-05 00:03 UTC, alvaroserrrano commented
Mmmm... I see, we should go to https://www.linkedin.com/in/linkedin-profile-name/detail/recent-activity/shares/ instead I guess. Do you know what the corresponding voyager endpoint would be or look like? Or do you have any clue that might help me find the post comments and see the reactions and what users made those reactions?