Feature/get posts comments
tomquirk/linkedin-api pull request #185
Opened 2021-10-13 22:50 UTC by alvaroserrrano

2021-10-13 22:52 UTC, alvaroserrrano commented
For some reason, it is still showing the commit message from a previous PR I made. I am not being able to only show the new changes that I am adding...

2021-10-20 13:16 UTC, alvaroserrrano commented
This current version falls under an infinite loop. We need to come up with an exit condition

2021-10-29 19:47 UTC, alvaroserrrano reviewed
I will look into it for the next commit

Also, I created a separate script for testing purposes, how could I install the latest version (master branch) of this project. When I look inside the venv the file does not have the function to get the posts for example, and that PR was merged into master. Maybe just try to explain how you would go about it from scratch. I have been using pip, poetry, and they worked, but for some reason I must be doing something wrong now

2021-11-01 05:51 UTC, abinpaul1 requested changes

2021-11-01 05:51 UTC, abinpaul1 commented on linkedin_api/linkedin.py
> +                if data["elements"] and len(data["elements"]) == 0:
I missed this initially, this would still keep on going because we are repeatedly checking data['elements'], it would never have zero elements. What we needed to check was `len(res.json()["elements"])`.

2021-11-01 05:54 UTC, abinpaul1 commented
> I will look into it for the next commit
> 
> Also, I created a separate script for testing purposes, how could I install the latest version (master branch) of this project. When I look inside the venv the file does not have the function to get the posts for example, and that PR was merged into master. Maybe just try to explain how you would go about it from scratch. I have been using pip, poetry, and they worked, but for some reason I must be doing something wrong now. This is the output from poetry: `• Installing linkedin-api (2.0.0a5)`

I think its because when you do a pip install it fetches the older version of `linkedin-api` package from PyPi. We will have to do a new release to incorporate the new changes. After we merge this PR, we could try for a new release.

2021-11-05 15:08 UTC, abinpaul1 commented on linkedin_api/linkedin.py
> +                if data["elements"] and len(res.json()["elements"]) == 0:
```python
if res.json()["elements"] and len(res.json()["elements"]) == 0:
```

2021-11-05 15:09 UTC, abinpaul1 reviewed
I think you missed out on updating the first condition.

2021-11-12 01:44 UTC, merged

2021-11-12 01:45 UTC, abinpaul1 commented
Good work 👌

2021-11-12 01:50 UTC, abinpaul1 commented
@tomquirk Would it be possible to do a pypi release based on the current master branch? A few new features have been added since the last release.