Feature: logout
tomquirk/linkedin-api pull request #197
Opened 2022-01-03 20:45 UTC by alvaroserrrano

2022-01-04 05:07 UTC, abinpaul1 commented on linkedin_api/linkedin.py
> +        url_params["updateId"] = "activity:" + post_urn
Why is this line required?

2022-01-04 05:13 UTC, abinpaul1 commented on linkedin_api/linkedin.py
> +        """GET request to log user out"""
I dont think its necessary to mention it is a GET request. It would be enough to just mention what the method does. In this case it could . `Logs out of the current session`.
What is your opinion on having a return type of `bool` which would be true on success and false on failure to logout.

2022-01-04 12:23 UTC, abinpaul1 requested changes

2022-01-04 12:23 UTC, abinpaul1 commented on linkedin_api/linkedin.py
>          if data and "status" in data and data["status"] != 200:
I think you forgot to remove these 3 lines.

2022-01-04 12:23 UTC, abinpaul1 commented on linkedin_api/linkedin.py
> +            return True
No harm in keeping the logging statement.

2022-01-04 12:28 UTC, abinpaul1 commented
Just confirming, did you try testing the other methods after logout. Ideally they shouldn’t  work and throw some errors after the logout. Could you please confirm the behaviour?

2022-03-02 11:15 UTC, engahmed1190 commented
@alvaroserrrano @abinpaul1  is this pull request valid, it is a very important feature logout from the current session. I have tried it and it returns `{'elements': [{'globalLegoTrackingToken': 'XXXX', 'legoTrackingToken': 'XXXX', 'takeoverType': 'ABI'}], 'paging': {'count': 10, 'start': 0, 'total': 1, 'links': []}}`

2022-03-02 11:38 UTC, abinpaul1 commented
I am not sure if the changes in this PR were tested. @alvaroserrrano can maybe conform. 

@engahmed1190 Are you able to use other methods after logout is called?
Maybe you could verify by visiting LinkedIn and cheking if the session is still active or not.  It can be viewed under Settings  -> Sign in & Security -> Account access -> Where you're signed in.

2022-03-02 12:38 UTC, engahmed1190 commented
The session is still active after using the `logout `

2022-03-02 13:28 UTC, abinpaul1 commented
Oh, then it seems we have missed some logic in the logout flow. We currently only do a get request to endpoint mentioned in  #191 . It requires further investigation i suppose

2024-08-26 22:09 UTC, closed without merging