fixed add_connection method
tomquirk/linkedin-api pull request #453
Opened 2024-11-01 15:00 UTC by yashdharme

This PR updates the `add_connection` function to align with the new endpoint and modified payload requirements for sending connection requests.

**Testing:**
- All relevant tests have been updated and successfully passed to ensure the changes work as intended.

Please review the changes, and let me know if any further modifications are needed!

2024-11-01 19:50 UTC, faizan-nexyom approved these changes

2024-11-02 11:22 UTC, pankajToday commented on linkedin_api/linkedin.py
> +                    "memberProfile": f"urn:li:fsd_profile:{profile_urn}"
I think you have forget to remove f from line number 1441  "memberProfile":  -----> f  "urn:li:

2024-11-02 17:42 UTC, yash-exela commented on linkedin_api/linkedin.py
> +                    "memberProfile": f"urn:li:fsd_profile:{profile_urn}"
He is using formatted string over there to dynamically take the profile_urn through the function from the user. It's correct and it's working actually. I just have tried to reflect the same changes in the original library installed in my site-packages as this guy has done in the PR and it worked.

2024-11-02 17:43 UTC, yash-exela approved these changes

2024-11-03 23:02 UTC, tomquirk requested changes
Hey @yashdharme thanks for this contribution and concise PR! Just left one comment 🙏 . Could you please also run `poetry run black .` for formatting?

2024-11-03 23:02 UTC, tomquirk commented on linkedin_api/linkedin.py
> +            return True
**question** we typically return `False` if an error occurred. Should this logic be flipped around?

2024-11-04 05:24 UTC, yashdharme commented on linkedin_api/linkedin.py
> +            return True
But you said the following in the doc string of the function:
`
return: Error state. True if error occurred
`
So I have kept it as it was earlier. If the request is sent successfully then method will return False else if error occurred it will return True.

2024-11-04 11:59 UTC, dino-exela commented
> Hey @yashdharme thanks for this contribution and concise PR! Just left one comment 🙏 . Could you please also run `poetry run black .` for formatting?

Done. Can you please check and revert?

2024-11-05 21:42 UTC, yashdharme commented
> Hey @yashdharme thanks for this contribution and concise PR! Just left one comment 🙏 . Could you please also run `poetry run black .` for formatting?



> Hey @yashdharme thanks for this contribution and concise PR! Just left one comment 🙏 . Could you please also run `poetry run black .` for formatting?

Done. Please check and revert back if further changes are required.

2024-11-07 08:04 UTC, tomquirk commented
Thank you @yashdharme ! Let's merge 🏁

2024-11-07 08:05 UTC, tomquirk approved these changes

2024-11-07 08:05 UTC, tomquirk commented on linkedin_api/linkedin.py
> +            return True
🤣 Sorry, that's my bad. You're 100% correct. Ignore me!

2024-11-07 08:06 UTC, merged