Add get_job_posting
tomquirk/linkedin-api pull request #83
Opened 2020-03-19 17:47 UTC by aeciorc

This method returns job posting details. The job_urn_id can be found in the "jobPosting" fields in the response of a linkedin.search for job postings,e.g:
```
      "jobPosting": "urn:li:fs_normalized_jobPosting:1754968923",
```

2020-04-19 09:25 UTC, tomquirk commented
@aeciorc LGTM! However, would you be able to add a test for this? Use the other ones as examples 😄

2020-06-02 10:54 UTC, tomquirk commented
@aeciorc wanted to double check that you were still interested in going ahead with this PR! Let me know if you need help with the tests.

2020-06-03 13:56 UTC, aeciorc commented
Hey @tomquirk, totally forgot about this PR, my bad. I'm still interested, I'll push some tests this weekend.

2020-09-09 10:17 UTC, tomquirk requested changes

2020-09-09 10:17 UTC, tomquirk commented on DOCS.md
> +<a name="get_job_posting"></a>
Could we move this to a docstring? The project now uses Sphinx for auto doc generation. Have a look at other functions for examples and ping me if you need help :)

2020-10-01 06:52 UTC, tomquirk commented
Bump!

2022-07-16 11:19 UTC, abinpaul1 commented
Added in https://github.com/tomquirk/linkedin-api/pull/234

2022-07-16 11:19 UTC, closed without merging